// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentResponse = { status: AgentStatus, thought: string | null, toolName: string | null, toolArgs: any, actionPrompt: string | null, nextAgent: AgentType | null, task: string | null, reason: string | null, };

export type AgentStatus = "TOOL_CALL" | "REQUIRE_USER_ACTION" | "SUCCESS" | "DEAD_END" | "BRANCHING";

export type AgentType = "TranslatorAgent";

export type Message = { role: string, content: string, };
