// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	lookupWord: (text: string) => typedError<LookupResult, string>(__TAURI_INVOKE("lookup_word", { text })),
	saveAgentLog: (filename: string, content: string) => typedError<null, string>(__TAURI_INVOKE("save_agent_log", { filename, content })),
	runStt: (videoPath: string, modelSize: string) => typedError<null, string>(__TAURI_INVOKE("run_stt", { videoPath, modelSize })),
	runAgentTask: (agentType: AgentType, payloadJson: string) => typedError<string, string>(__TAURI_INVOKE("run_agent_task", { agentType, payloadJson })),
};

/* Types */
export type AgentType = "TranslatorAgent";

export type DictionaryEntry = {
	id: string,
	kanji: string[],
	kana: string[],
	glossary: string[],
};

export type LookupResult = {
	original_text: string,
	token: string,
	base_form: string,
	reading: string,
	entries: DictionaryEntry[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

