// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	lookupWord: (text: string) => typedError<LookupResult, string>(__TAURI_INVOKE("lookup_word", { text })),
	getFurigana: (text: string) => typedError<FuriganaToken[], string>(__TAURI_INVOKE("get_furigana", { text })),
	startSttJob: (videoPath: string, modelSize: string, language: string, vadEngine: string, mssEngine: string, mssModel: string, useBatch: boolean, batchSize: number) => typedError<string, string>(__TAURI_INVOKE("start_stt_job", { videoPath, modelSize, language, vadEngine, mssEngine, mssModel, useBatch, batchSize })),
	cancelSttJob: (jobId: string) => typedError<null, string>(__TAURI_INVOKE("cancel_stt_job", { jobId })),
	getSttJobState: () => typedError<{
	job_id: string,
	status: SttStatus,
	progress: number,
	language: string | null,
	error_message: string | null,
	runtime_device: string | null,
	runtime_compute_type: string | null,
	vocals_path: string | null,
	instrumental_path: string | null,
} | null, string>(__TAURI_INVOKE("get_stt_job_state")),
	importSttResults: (results: STTResult[]) => typedError<null, string>(__TAURI_INVOKE("import_stt_results", { results })),
	startTranslation: () => typedError<null, string>(__TAURI_INVOKE("start_translation")),
	runAgentTask: (agentType: AgentType, payloadJson: string) => typedError<string, string>(__TAURI_INVOKE("run_agent_task", { agentType, payloadJson })),
	getAppState: () => typedError<ProjectState, string>(__TAURI_INVOKE("get_app_state")),
};

/* Types */
export type AgentType = "TranslatorAgent";

export type DictionaryEntry = {
	id: string,
	headwords: string[],
	pronunciations: string[],
	tags: string[],
	glossary: string[],
};

export type FuriganaToken = {
	surface: string,
	reading: string | null,
};

export type LookupResult = {
	original_text: string,
	token: string,
	base_form: string,
	reading: string | null,
	entries: DictionaryEntry[],
};

export type ProjectState = {
	video_path: string | null,
	stt_status: STTStatus,
	stt_error_message: string | null,
	stt_progress: number | null,
	translation_status: TranslationStatus,
	translation_progress: number | null,
	results: STTResult[],
	target_language: string,
	vocals_audio_path: string | null,
	background_audio_path: string | null,
};

export type STTResult = {
	start: number | null,
	end: number | null,
	text: string,
	translation: string | null,
};

export type STTStatus = "idle" | "loading_model" | "transcribing" | "completed" | "error";

export type SttJobSnapshot = {
	job_id: string,
	status: SttStatus,
	progress: number,
	language: string | null,
	error_message: string | null,
	runtime_device: string | null,
	runtime_compute_type: string | null,
	vocals_path: string | null,
	instrumental_path: string | null,
};

export type SttStatus = "idle" | "starting" | "loading_model" | "transcribing" | "cancelling" | "completed" | "cancelled" | "failed";

export type TranslationStatus = "idle" | "translating" | "completed" | "error";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

