// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	lookupWord: (text: string, index: number) => typedError<LookupResult[], string>(__TAURI_INVOKE("lookup_word", { text, index })),
	getFurigana: (text: string) => typedError<FuriganaToken[], string>(__TAURI_INVOKE("get_furigana", { text })),
	triggerPipeline: (args: PipelineConfig) => typedError<string, string>(__TAURI_INVOKE("trigger_pipeline", { args })),
	cancelPipeline: () => typedError<null, string>(__TAURI_INVOKE("cancel_pipeline")),
	importPipelineResults: (results: STTResult[]) => typedError<null, string>(__TAURI_INVOKE("import_pipeline_results", { results })),
	startTranslation: (targetLanguage: string) => typedError<null, string>(__TAURI_INVOKE("start_translation", { targetLanguage })),
	runAgentTask: (agentType: AgentType, payloadJson: string) => typedError<string, string>(__TAURI_INVOKE("run_agent_task", { agentType, payloadJson })),
	startSegmentation: () => typedError<null, string>(__TAURI_INVOKE("start_segmentation")),
	getAppState: () => typedError<ProjectState, string>(__TAURI_INVOKE("get_app_state")),
};

/* Types */
export type AgentType = "TranslatorAgent" | "SegmenterAgent";

export type DictionaryEntry = {
	id: string,
	headwords: string[],
	pronunciations: string[],
	tags: string[],
	glossary: string[],
};

export type FuriganaToken = {
	surface: string,
	reading: string | null,
};

export type LookupResult = {
	original_text: string,
	token: string,
	base_form: string,
	reading: string | null,
	entries: DictionaryEntry[],
};

export type PipelineConfig = {
	videoPath: string,
	modelSize: string,
	language: string,
	vadEngine: string,
	mssEngine: string,
	mssModel: string,
	faEngine: string,
	faModel: string,
	useBatch: boolean,
	batchSize: number,
	enableSegmentation: boolean,
	enableTranslation: boolean,
	targetLanguage: string,
};

export type PipelineTask = {
	task_type: TaskType,
	status: TaskStatus,
	progress: number | null,
	error_message: string | null,
};

export type ProjectState = {
	video_path: string | null,
	extracted_audio_path: string | null,
	tasks: PipelineTask[],
	results: STTResult[],
	target_language: string,
	vocals_audio_path: string | null,
	background_audio_path: string | null,
	stt_model_size: string | null,
	vad_engine: string | null,
	mss_engine: string | null,
	mss_model: string | null,
	fa_engine: string | null,
	fa_model: string | null,
	use_batch: boolean,
	batch_size: number,
};

export type STTResult = {
	start: number | null,
	end: number | null,
	text: string,
	translation: string | null,
	words: WordTiming[] | null,
};

export type TaskStatus = "pending" | "running" | "completed" | "error" | "cancelled" | "outdated";

export type TaskType = "preprocess" | "mss" | "vad" | "stt" | "forced_alignment" | "translation" | "segmentation";

export type WordTiming = {
	text: string,
	start: number | null,
	end: number | null,
	probability: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

